import '@testing-library/jest-dom';
import '@types/jest';
import '@types/node';

declare module '*.jpg';
declare module '*.svg';
declare module '*.png';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.ico';
declare module '*.eot';
declare module '*.otf';
declare module '*.webp';
declare module '*.svg';
declare module '*.ttf';
declare module '*.woff';
declare module '*.woff2';
declare module '*.mp4';
declare module '*.webm';
declare module '*.wav';
declare module '*.mp3';
declare module '*.m4a';
declare module '*.aac';
declare module '*.oga';